"""ayah phoneme_ids v1

Revision ID: 5966d3da708d
Revises: 8d136d972aad
Create Date: 2026-06-13 13:22:45.402697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5966d3da708d'
down_revision: Union[str, None] = '8d136d972aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ayahs', sa.Column('phoneme_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ayahs', sa.Column('phoneme_confidence', sa.Float(), nullable=True))
    op.add_column('ayahs', sa.Column('phoneme_unstable', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ayahs', 'phoneme_unstable')
    op.drop_column('ayahs', 'phoneme_confidence')
    op.drop_column('ayahs', 'phoneme_ids')
    # ### end Alembic commands ###
