"""baseline

Revision ID: 5e8adb8274b8
Revises: 
Create Date: 2026-06-12 19:15:45.217491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5e8adb8274b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_arabic', sa.String(length=64), nullable=False),
    sa.Column('name_english', sa.String(length=64), nullable=False),
    sa.Column('ayah_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ayahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('verse_key', sa.String(length=8), nullable=False),
    sa.Column('text_uthmani', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['surah_id'], ['surahs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surah_id', 'number', name='uq_ayah_surah_number')
    )
    op.create_index(op.f('ix_ayahs_verse_key'), 'ayahs', ['verse_key'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('start_ayah', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['surah_id'], ['surahs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mutashabeh_pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_ayah_id', sa.Integer(), nullable=False),
    sa.Column('target_ayah_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_ayah_id'], ['ayahs.id'], ),
    sa.ForeignKeyConstraint(['target_ayah_id'], ['ayahs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ayah_id', 'target_ayah_id', name='uq_mutashabeh_pair')
    )
    op.create_index('ix_mutashabeh_source', 'mutashabeh_pairs', ['source_ayah_id'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_session_ts', 'session_events', ['session_id', 'ts'], unique=False)
    op.create_table('session_summaries',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('words_ok', sa.Integer(), nullable=False),
    sa.Column('words_missed', sa.Integer(), nullable=False),
    sa.Column('ayahs_missed', sa.Integer(), nullable=False),
    sa.Column('jumps', sa.Integer(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_uthmani', sa.String(length=64), nullable=False),
    sa.Column('text_imlaei', sa.String(length=64), nullable=False),
    sa.Column('text_normalized', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ayah_id', 'position', name='uq_word_ayah_position')
    )
    op.create_index('ix_words_ayah_position', 'words', ['ayah_id', 'position'], unique=False)
    op.create_index(op.f('ix_words_text_normalized'), 'words', ['text_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_text_normalized'), table_name='words')
    op.drop_index('ix_words_ayah_position', table_name='words')
    op.drop_table('words')
    op.drop_table('session_summaries')
    op.drop_index('ix_events_session_ts', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('ix_mutashabeh_source', table_name='mutashabeh_pairs')
    op.drop_table('mutashabeh_pairs')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_ayahs_verse_key'), table_name='ayahs')
    op.drop_table('ayahs')
    op.drop_table('surahs')
    # ### end Alembic commands ###
