"""nullable session location for auto-detect

Revision ID: 8d136d972aad
Revises: 5e8adb8274b8
Create Date: 2026-06-12 19:39:48.677599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d136d972aad'
down_revision: Union[str, None] = '5e8adb8274b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'surah_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'start_ayah',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'start_ayah',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'surah_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
